#ifndef SERIAL_SEND_NODE_H
#define SERIAL_SEND_NODE_H

#define UNION_UCHAR_SIZE 8
#define GIMBAL_MODE_BUFFER_SIZE 2
#define GIMBAL_ANGLE_BUFFER_SIZE (2 * UNION_UCHAR_SIZE)
#define OUTPUT_BUFFER_SIZE (GIMBAL_MODE_BUFFER_SIZE + GIMBAL_ANGLE_BUFFER_SIZE)

#define GIMBAL_YAW_MODE_BUFFER_OFFSET     0
#define GIMBAL_YAW_MODE_BUFFER_SIZE       1
#define GIMBAL_PITCH_MODE_BUFFER_OFFSET   (GIMBAL_YAW_MODE_BUFFER_OFFSET + GIMBAL_YAW_MODE_BUFFER_SIZE)
#define GIMBAL_PITCH_MODE_BUFFER_SIZE     1
#define GIMBEL_YAW_ANGLE_BUFFER_OFFSET    (GIMBAL_PITCH_MODE_BUFFER_OFFSET + GIMBAL_PITCH_MODE_BUFFER_SIZE)
#define GIMBEL_YAW_ANGLE_BUFFER_SIZE      (GIMBAL_ANGLE_BUFFER_SIZE)
#define GIMBEL_PITCH_ANGLE_BUFFER_OFFSET  (GIMBEL_YAW_ANGLE_BUFFER_OFFSET + GIMBEL_YAW_ANGLE_BUFFER_SIZE)
#define GIMBEL_PITCH_ANGLE_BUFFER_SIZE    (GIMBAL_ANGLE_BUFFER_SIZE)

#define GIMBAL_YAW_CMD_PID_KP 0.005f
#define GIMBAL_PITCH_CMD_PID_KP 0.007f
#define GIMBAL_YAW_CMD_PID_KD 0.07f
#define GIMBAL_PITCH_CMD_PID_KD 0.002f

#define GIMBAL_YAW_CMD_MAX 0.0008f
#define GIMBAL_YAW_CMD_MIN -0.0008f
#define GIMBAL_PITCH_CMD_MAX 0.0012f
#define GIMBAL_PITCH_CMD_MIN -0.0012f

typedef struct 
{
    uint8_t yaw_mode;
    uint8_t pitch_mode;
    double yaw_angle;
    double pitch_angle;
}serial_send_t;


typedef union 
{
    double double_data;
    uint8_t uchar_data[UNION_UCHAR_SIZE];
}f64_uchar_u;


#endif

